[tox]
envlist = py312,quality
requires = tox-uv>=1
skip_missing_interpreters = True

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    coverage run -m pytest
    coverage report

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pycodestyle --config=.pep8 src/calc src/symmath tests
    pylint --rcfile=pylintrc src/calc src/symmath tests
